class Error(Exception):
    pass

class LoginFailed(Exception):
    pass